SYMBOLS = [
    {"s": "RELIANCE",   "n": "Reliance Industries",          "e": "NSE"},
    {"s": "TCS",        "n": "Tata Consultancy Services",     "e": "NSE"},
    {"s": "HDFCBANK",   "n": "HDFC Bank",                     "e": "NSE"},
    {"s": "INFY",       "n": "Infosys",                       "e": "NSE"},
    {"s": "ICICIBANK",  "n": "ICICI Bank",                    "e": "NSE"},
    {"s": "HINDUNILVR", "n": "Hindustan Unilever",            "e": "NSE"},
    {"s": "ITC",        "n": "ITC Limited",                   "e": "NSE"},
    {"s": "SBIN",       "n": "State Bank of India",           "e": "NSE"},
    {"s": "BHARTIARTL", "n": "Bharti Airtel",                 "e": "NSE"},
    {"s": "KOTAKBANK",  "n": "Kotak Mahindra Bank",           "e": "NSE"},
    {"s": "BAJFINANCE", "n": "Bajaj Finance",                 "e": "NSE"},
    {"s": "BAJAJFINSV", "n": "Bajaj Finserv",                 "e": "NSE"},
    {"s": "LT",         "n": "Larsen & Toubro",               "e": "NSE"},
    {"s": "HCLTECH",    "n": "HCL Technologies",              "e": "NSE"},
    {"s": "ASIANPAINT", "n": "Asian Paints",                  "e": "NSE"},
    {"s": "AXISBANK",   "n": "Axis Bank",                     "e": "NSE"},
    {"s": "WIPRO",      "n": "Wipro",                         "e": "NSE"},
    {"s": "MARUTI",     "n": "Maruti Suzuki",                 "e": "NSE"},
    {"s": "SUNPHARMA",  "n": "Sun Pharmaceutical",            "e": "NSE"},
    {"s": "ULTRACEMCO", "n": "UltraTech Cement",              "e": "NSE"},
    {"s": "TITAN",      "n": "Titan Company",                 "e": "NSE"},
    {"s": "NESTLEIND",  "n": "Nestle India",                  "e": "NSE"},
    {"s": "TECHM",      "n": "Tech Mahindra",                 "e": "NSE"},
    {"s": "TATAMOTORS", "n": "Tata Motors",                   "e": "NSE"},
    {"s": "TATASTEEL",  "n": "Tata Steel",                    "e": "NSE"},
    {"s": "NTPC",       "n": "NTPC Limited",                  "e": "NSE"},
    {"s": "POWERGRID",  "n": "Power Grid Corp",               "e": "NSE"},
    {"s": "ONGC",       "n": "Oil & Natural Gas Corp",        "e": "NSE"},
    {"s": "JSWSTEEL",   "n": "JSW Steel",                     "e": "NSE"},
    {"s": "COALINDIA",  "n": "Coal India",                    "e": "NSE"},
    {"s": "DRREDDY",    "n": "Dr. Reddy's Labs",              "e": "NSE"},
    {"s": "CIPLA",      "n": "Cipla",                         "e": "NSE"},
    {"s": "HEROMOTOCO", "n": "Hero MotoCorp",                 "e": "NSE"},
    {"s": "EICHERMOT",  "n": "Eicher Motors",                 "e": "NSE"},
    {"s": "BPCL",       "n": "Bharat Petroleum",              "e": "NSE"},
    {"s": "HINDALCO",   "n": "Hindalco Industries",           "e": "NSE"},
    {"s": "DIVISLAB",   "n": "Divi's Laboratories",           "e": "NSE"},
    {"s": "ADANIPORTS", "n": "Adani Ports & SEZ",             "e": "NSE"},
    {"s": "IRCTC",      "n": "Indian Railway Catering Corp",  "e": "NSE"},
    {"s": "DMART",      "n": "Avenue Supermarts (DMart)",     "e": "NSE"},
    {"s": "NAUKRI",     "n": "Info Edge (Naukri.com)",        "e": "NSE"},
    {"s": "PERSISTENT", "n": "Persistent Systems",            "e": "NSE"},
    {"s": "MPHASIS",    "n": "Mphasis",                       "e": "NSE"},
    {"s": "HAVELLS",    "n": "Havells India",                 "e": "NSE"},
    {"s": "SIEMENS",    "n": "Siemens India",                 "e": "NSE"},
    {"s": "MRF",        "n": "MRF Tyres",                     "e": "NSE"},
    {"s": "TRENT",      "n": "Trent Limited",                 "e": "NSE"},
    {"s": "TVSMOTOR",   "n": "TVS Motor Company",             "e": "NSE"},
    {"s": "DLF",        "n": "DLF Limited",                   "e": "NSE"},
    {"s": "YESBANK",    "n": "Yes Bank",                      "e": "NSE"},
    {"s": "PNB",        "n": "Punjab National Bank",          "e": "NSE"},
    {"s": "VEDL",       "n": "Vedanta Limited",               "e": "NSE"},
    {"s": "GODREJCP",   "n": "Godrej Consumer Products",      "e": "NSE"},
    {"s": "DABUR",      "n": "Dabur India",                   "e": "NSE"},
    {"s": "LUPIN",      "n": "Lupin Limited",                 "e": "NSE"},
    {"s": "BIOCON",     "n": "Biocon",                        "e": "NSE"},
    {"s": "INDHOTEL",   "n": "Indian Hotels (Taj)",           "e": "NSE"},
    {"s": "AAPL",       "n": "Apple Inc.",                    "e": "NASDAQ"},
    {"s": "MSFT",       "n": "Microsoft Corp.",               "e": "NASDAQ"},
    {"s": "GOOGL",      "n": "Alphabet (Google)",             "e": "NASDAQ"},
    {"s": "AMZN",       "n": "Amazon.com",                    "e": "NASDAQ"},
    {"s": "META",       "n": "Meta Platforms (Facebook)",     "e": "NASDAQ"},
    {"s": "NVDA",       "n": "NVIDIA Corp.",                  "e": "NASDAQ"},
    {"s": "TSLA",       "n": "Tesla Inc.",                    "e": "NASDAQ"},
    {"s": "JPM",        "n": "JPMorgan Chase",                "e": "NYSE"},
    {"s": "V",          "n": "Visa Inc.",                     "e": "NYSE"},
    {"s": "BAC",        "n": "Bank of America",               "e": "NYSE"},
    {"s": "NFLX",       "n": "Netflix Inc.",                  "e": "NASDAQ"},
    {"s": "DIS",        "n": "Walt Disney Co.",               "e": "NYSE"},
    {"s": "ADBE",       "n": "Adobe Inc.",                    "e": "NASDAQ"},
    {"s": "AMD",        "n": "Advanced Micro Devices",        "e": "NASDAQ"},
    {"s": "INTC",       "n": "Intel Corp.",                   "e": "NASDAQ"},
    {"s": "PYPL",       "n": "PayPal Holdings",               "e": "NASDAQ"},
    {"s": "UBER",       "n": "Uber Technologies",             "e": "NYSE"},
    {"s": "SHOP",       "n": "Shopify Inc.",                  "e": "NYSE"},
    {"s": "PLTR",       "n": "Palantir Technologies",         "e": "NASDAQ"},
]


def search_symbols(query: str, limit: int = 10):
    q = query.strip().upper()
    if not q:
        return []
    return [
        {"symbol": s["s"], "name": s["n"], "exchange": s["e"]}
        for s in SYMBOLS
        if q in s["s"].upper() or q in s["n"].upper()
    ][:limit]
